# Generated by Django 6.1 on 2026-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('air_temperature', models.FloatField(verbose_name="Température de l'air (K)")),
                ('process_temperature', models.FloatField(verbose_name='Température du process (K)')),
                ('rotational_speed', models.FloatField(verbose_name='Vitesse de rotation (rpm)')),
                ('torque', models.FloatField(verbose_name='Couple (Nm)')),
                ('tool_wear', models.FloatField(verbose_name="Usure de l'outil (min)")),
                ('reconstruction_error', models.FloatField()),
                ('threshold', models.FloatField()),
                ('is_anomaly', models.BooleanField(db_index=True)),
                ('severity_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lecture capteur',
                'verbose_name_plural': 'Lectures capteurs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
