# Generated by Django 6.1 on 2026-08-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='flag_comment',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='flagged',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Signalée comme incorrecte'),
        ),
    ]
