# Generated by Django 5.2.17 on 2026-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_sensorreading_flag_comment_sensorreading_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
