# Generated by Django 5.2.17 on 2026-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_sensorreading_model_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
